# Generated by Django 6.0.1 on 2026-01-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_curso_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
