# Generated by Django 6.0.1 on 2026-01-22 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_curso_creditos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='ciclo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.ciclo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='tipo_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestion.tipocurso'),
        ),
    ]
