# Generated by Django 6.0.1 on 2026-01-22 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_curso_ciclo_alter_curso_tipo_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='aula',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.aula'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestion.docente'),
        ),
    ]
