# Generated by Django 6.0.1 on 2026-02-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_horario_aula_alter_horario_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='apellido',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
