# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=100)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Institucional')),
                ('tipo', models.CharField(choices=[('N', 'Nombrado'), ('C', 'Contratado')], default='C', max_length=1)),
                ('codigo', models.CharField(blank=True, help_text='Obligatorio solo para docentes nombrados', max_length=20, null=True, unique=True, verbose_name='Código Docente')),
                ('categoria', models.CharField(blank=True, choices=[('PRI', 'Principal'), ('ASO', 'Asociado'), ('AUX', 'Auxiliar')], max_length=3, null=True)),
                ('dedicacion', models.CharField(blank=True, choices=[('DE', 'Dedicación Exclusiva'), ('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial')], max_length=2, null=True, verbose_name='Clase/Dedicación')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el docente está activo en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='facultades.departamento', verbose_name='Departamento Académico')),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes', to='facultades.facultad', verbose_name='Facultad de Adscripción')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
    ]
