# Generated by Django 6.0.1 on 2026-02-15 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('facultades', '0002_departamento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='docente',
            options={'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.RenameField(
            model_name='docente',
            old_name='nombre',
            new_name='nombres',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='apellido',
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_materno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='categoria',
            field=models.CharField(blank=True, choices=[('PRI', 'Principal'), ('ASO', 'Asociado'), ('AUX', 'Auxiliar')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='codigo',
            field=models.CharField(blank=True, help_text='Obligatorio solo para docentes nombrados', max_length=20, null=True, unique=True, verbose_name='Código Docente'),
        ),
        migrations.AddField(
            model_name='docente',
            name='dedicacion',
            field=models.CharField(blank=True, choices=[('DE', 'Dedicación Exclusiva'), ('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial')], max_length=2, null=True, verbose_name='Clase/Dedicación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='docentes', to='facultades.departamento'),
        ),
        migrations.AddField(
            model_name='docente',
            name='dni',
            field=models.CharField(default=1, max_length=8, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='docente',
            name='tipo',
            field=models.CharField(choices=[('N', 'Nombrado'), ('C', 'Contratado')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Correo Institucional'),
        ),
    ]
