# Generated by Django 6.0.1 on 2026-02-15 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0002_alter_docente_options_rename_nombre_docente_nombres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='activo',
            field=models.BooleanField(default=True, help_text='Indica si el docente está activo en el sistema', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 2, 15, 1, 32, 14, 665800, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
