# Generated by Django 6.0.1 on 2026-01-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, unique=True)),
                ('codigo', models.CharField(editable=False, max_length=6, unique=True)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escuelas', to='facultades.facultad')),
            ],
            options={
                'verbose_name': 'Escuela Profesional',
                'verbose_name_plural': 'Escuelas Profesionales',
                'ordering': ('codigo',),
            },
        ),
    ]
