# Generated by Django 6.0.2 on 2026-02-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escuela',
            name='codigo',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
