# Generated by Django 6.0.1 on 2026-01-21 05:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de asignatura')),
                ('tipo', models.CharField(choices=[('O', 'Obligatorio'), ('E', 'Electivo'), ('OP', 'Optativo'), ('AL', 'Alternativo')], default='O', max_length=2, verbose_name='Tipo de asignatura')),
                ('nombre', models.CharField(max_length=50)),
                ('creditos', models.PositiveIntegerField()),
                ('horas_teoria', models.PositiveSmallIntegerField(default=0)),
                ('horas_practica', models.PositiveSmallIntegerField(default=0)),
                ('horas_laboratorio', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planes.planestudios')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='asignaturas.ciclo')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['ciclo__numero', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos_set', to='asignaturas.asignatura')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras_set', to='asignaturas.asignatura')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'unique_together': {('asignatura', 'prerequisito')},
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='sucesoras', through='asignaturas.Prerequisito', to='asignaturas.asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('codigo', 'plan')},
        ),
    ]
