# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Ciclo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('O', 'Obligatorio'), ('E', 'Electivo'), ('OP', 'Optativo'), ('AL', 'Alternativo')], default='O', max_length=5, verbose_name='Tipo')),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.PositiveIntegerField()),
                ('horas_teoria', models.PositiveSmallIntegerField(default=0)),
                ('horas_practica', models.PositiveSmallIntegerField(default=0)),
                ('horas_laboratorio', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planes.planestudios')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'ordering': ['ciclo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre común de la equivalencia', max_length=200)),
                ('asignaturas', models.ManyToManyField(related_name='equivalencias', to='asignaturas.asignatura')),
            ],
            options={
                'verbose_name': 'Equivalencia',
                'verbose_name_plural': 'Equivalencias',
            },
        ),
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos_set', to='asignaturas.asignatura')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras_set', to='asignaturas.asignatura')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'unique_together': {('asignatura', 'prerequisito')},
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='sucesoras', through='asignaturas.Prerequisito', to='asignaturas.asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('codigo', 'plan')},
        ),
    ]
