# Generated by Django 6.0.1 on 2026-01-15 06:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de asignatura')),
                ('nombre', models.CharField(max_length=100)),
                ('creditos', models.PositiveIntegerField()),
                ('ciclo', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas', to='planes.planestudios')),
            ],
            options={
                'ordering': ['ciclo', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos_set', to='asignaturas.asignatura')),
                ('prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucesoras_set', to='asignaturas.asignatura')),
            ],
            options={
                'unique_together': {('asignatura', 'prerequisito')},
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='prerequisitos',
            field=models.ManyToManyField(related_name='sucesoras', through='asignaturas.Prerequisito', to='asignaturas.asignatura'),
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('codigo', 'plan')},
        ),
    ]
