# Generated by Django 6.0.1 on 2026-01-15 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['ciclo', 'codigo'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('O', 'Obligatorio'), ('E', 'Electivo'), ('OP', 'Optativo'), ('AL', 'Alternativo')], default='O', max_length=2, verbose_name='Tipo de asignatura'),
        ),
    ]
