# Generated by Django 6.0.1 on 2026-01-21 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_alter_asignatura_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura_equivalente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sirve_como_equivalencia', to='asignaturas.asignatura', verbose_name='Asignatura Equivalente (Oferta)')),
                ('asignatura_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='es_objetivo_de_equivalencia', to='asignaturas.asignatura', verbose_name='Asignatura Objetivo (Malla)')),
            ],
            options={
                'verbose_name': 'Equivalencia',
                'verbose_name_plural': 'Equivalencias',
                'unique_together': {('asignatura_objetivo', 'asignatura_equivalente')},
            },
        ),
    ]
