# Generated by Django 6.0.1 on 2026-01-21 04:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_alter_asignatura_options_asignatura_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'verbose_name': 'Ciclo',
                'verbose_name_plural': 'Ciclos',
                'ordering': ['numero'],
            },
        ),
        migrations.AlterModelOptions(
            name='asignatura',
            options={'ordering': ['ciclo__numero', 'codigo'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='prerequisito',
            options={'verbose_name': 'Prerrequisito', 'verbose_name_plural': 'Prerrequisitos'},
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_laboratorio',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_practica',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='horas_teoria',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='prerequisitos',
            field=models.ManyToManyField(blank=True, related_name='sucesoras', through='asignaturas.Prerequisito', to='asignaturas.asignatura'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaturas', to='asignaturas.ciclo'),
        ),
    ]
