# Generated by Django 6.0.1 on 2026-01-25 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0003_equivalencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=20, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('O', 'Obligatorio'), ('E', 'Electivo'), ('OP', 'Optativo'), ('AL', 'Alternativo')], default='O', max_length=2, verbose_name='Tipo'),
        ),
    ]
