# Generated by Django 6.0.1 on 2026-01-25 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0004_alter_asignatura_codigo_alter_asignatura_tipo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equivalencia',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='equivalencia',
            name='asignaturas',
            field=models.ManyToManyField(related_name='equivalencias', to='asignaturas.asignatura'),
        ),
        migrations.AddField(
            model_name='equivalencia',
            name='nombre',
            field=models.CharField(default='prueba', help_text='Nombre común de la equivalencia', max_length=150),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='equivalencia',
            name='asignatura_equivalente',
        ),
        migrations.RemoveField(
            model_name='equivalencia',
            name='asignatura_objetivo',
        ),
    ]
