# Generated by Django 6.0.2 on 2026-02-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0005_alter_equivalencia_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='codigo',
            field=models.CharField(max_length=50, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='tipo',
            field=models.CharField(choices=[('O', 'Obligatorio'), ('E', 'Electivo'), ('OP', 'Optativo'), ('AL', 'Alternativo')], default='O', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='equivalencia',
            name='nombre',
            field=models.CharField(help_text='Nombre común de la equivalencia', max_length=200),
        ),
    ]
