# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('siglas', models.CharField(max_length=50, unique=True, verbose_name='Siglas')),
                ('codigo', models.PositiveSmallIntegerField(unique=True, verbose_name='Código')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='facultades.facultad')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'unique_together': {('facultad', 'nombre')},
            },
        ),
    ]
