# Generated by Django 6.0.2 on 2026-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0002_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultad',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nombre'),
        ),
    ]
