# Generated by Django 6.0.2 on 2026-02-28 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultades', '0003_alter_facultad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='facultad',
            name='siglas',
            field=models.CharField(max_length=50, unique=True, verbose_name='Siglas'),
        ),
    ]
