# Generated by Django 6.0.2 on 2026-02-21 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='asignatura',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='aula',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='docente',
        ),
        migrations.RemoveField(
            model_name='grupo',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='grupo',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='Aula',
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='PeriodoAcademico',
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
    ]
