# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(help_text='Ingrese el año de vigencia (ej. 2023)', validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año del Plan')),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='escuelas.escuela')),
            ],
            options={
                'verbose_name': 'Plan de Estudios',
                'verbose_name_plural': 'Planes de Estudios',
                'ordering': ['-anio'],
                'unique_together': {('anio', 'escuela')},
            },
        ),
    ]
