# Generated by Django 6.0.1 on 2026-01-21 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('escuela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='escuelas.escuela')),
            ],
            options={
                'unique_together': {('nombre', 'escuela')},
            },
        ),
    ]
