# Generated by Django 6.0.1 on 2026-01-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('docentes', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='asignaturas.asignatura')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_asignados', to='docentes.docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='periodos.periodoacademico')),
            ],
            options={
                'verbose_name': 'Grupo',
                'ordering': ['periodo', 'asignatura', 'nombre'],
                'unique_together': {('nombre', 'asignatura', 'periodo')},
            },
        ),
    ]
