# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='asignaturas.asignatura')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='periodos.periodoacademico')),
            ],
            options={
                'verbose_name': 'Grupo',
                'ordering': ['periodo', 'asignatura', 'numero'],
                'unique_together': {('numero', 'asignatura', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DistribucionVacantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(help_text='Número de cupos reservados para este plan', verbose_name='Cantidad de Vacantes')),
                ('matriculados', models.PositiveIntegerField(default=0)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignaturas.asignatura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacantes', to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'Distribución de Vacante',
                'verbose_name_plural': 'Distribución de Vacantes',
                'unique_together': {('grupo', 'asignatura')},
            },
        ),
    ]
