# Generated by Django 6.0.2 on 2026-03-13 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('grupos', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
                model_name='grupo',
                old_name='asignatura',
                new_name='asignatura_base',
            ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['periodo', 'asignatura_base', 'numero'], 'verbose_name': 'Grupo'},
        ),
        migrations.AlterUniqueTogether(
            name='grupo',
            unique_together={('numero', 'asignatura_base', 'periodo')},
        ),
        migrations.CreateModel(
            name='GrupoAsignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacantes', models.PositiveIntegerField(default=0, verbose_name='Vacantes reservadas')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='asignaturas.asignatura')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaturas_cubiertas', to='grupos.grupo')),
            ],
            options={
                'verbose_name': 'Asignatura cubierta por grupo',
                'unique_together': {('grupo', 'asignatura')},
            },
        ),
        migrations.AddField(
            model_name='grupo',
            name='asignaturas',
            field=models.ManyToManyField(blank=True, related_name='grupos', through='grupos.GrupoAsignatura', to='asignaturas.asignatura'),
        ),
        migrations.DeleteModel(
            name='DistribucionVacantes',
        ),
    ]
