# Generated by Django 6.0.1 on 2026-02-14 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='docente',
        ),
    ]
