# Generated by Django 6.0.1 on 2026-01-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0002_alter_asignatura_options_asignatura_tipo'),
        ('grupos', '0001_initial'),
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='asignatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='asignaturas.asignatura'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='periodos.periodoacademico'),
        ),
    ]
