# Generated by Django 6.0.2 on 2026-03-18 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignaturas', '0001_initial'),
        ('grupos', '0002_alter_grupo_options_alter_grupo_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='asignatura_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_base', to='asignaturas.asignatura'),
        ),
    ]
