# Generated by Django 6.0.2 on 2026-02-26 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_remove_grupo_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='numero',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
