# Generated by Django 6.0.2 on 2026-03-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('SEMESTRE', 'Semestre'), ('ANUAL', 'Anual'), ('VERANO', 'Cursos de Verano')], default='SEMESTRE', max_length=10)),
                ('anio', models.PositiveSmallIntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fuente', models.URLField(blank=True, help_text='Link a la resolución o página web', null=True)),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'ordering': ['-anio', '-fecha_inicio'],
            },
        ),
    ]
