# Generated by Django 6.0.1 on 2026-02-15 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodoacademico',
            name='fuente',
            field=models.URLField(blank=True, help_text='Link a la resolución o página web', null=True),
        ),
    ]
