# Generated by Django 6.0.1 on 2026-02-24 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0002_departamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 101 NP, 203 AP, LAB 2', max_length=20, unique=True, verbose_name='Nombre del Aula')),
                ('pabellon', models.CharField(choices=[('AP', 'Antiguo Pabellón'), ('NP', 'Nuevo Pabellón')], max_length=3, verbose_name='Pabellón')),
                ('vacantes', models.PositiveIntegerField(help_text='Capacidad máxima de alumnos', verbose_name='Vacantes')),
                ('tipo_sesion', models.CharField(choices=[('T', 'Teoría'), ('P', 'Práctica')], default='T', help_text='Define si el aula es para Teoría o Práctica', max_length=1, verbose_name='Tipo de Sesión')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el aula está disponible en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('facultad', models.ForeignKey(help_text='Facultad a la que pertenece el aula', on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='facultades.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['pabellon', 'nombre'],
            },
        ),
    ]
