# Generated by Django 6.0.1 on 2026-01-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('TEORIA', 'Teoría'), ('LAB', 'Laboratorio')], max_length=20)),
                ('capacidad', models.PositiveIntegerField()),
            ],
        ),
    ]
