# Generated by Django 6.0.2 on 2026-03-12 06:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facultades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: 101 NP, 203 AP, LAB 2', max_length=20, verbose_name='Nombre del Aula')),
                ('pabellon', models.CharField(choices=[('AP', 'Antiguo Pabellón'), ('NP', 'Nuevo Pabellón')], max_length=3, verbose_name='Pabellón')),
                ('vacantes', models.PositiveIntegerField(help_text='Capacidad máxima de alumnos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vacantes')),
                ('tipo', models.CharField(choices=[('A', 'Aula'), ('L', 'Laboratorio')], default='A', max_length=1, verbose_name='Tipo de Aula')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el aula está disponible en el sistema', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('facultad', models.ForeignKey(help_text='Facultad a la que pertenece el aula', on_delete=django.db.models.deletion.CASCADE, related_name='aulas', to='facultades.facultad', verbose_name='Facultad')),
            ],
            options={
                'verbose_name': 'Aula',
                'verbose_name_plural': 'Aulas',
                'ordering': ['pabellon', 'nombre'],
                'unique_together': {('nombre', 'pabellon')},
            },
        ),
    ]
