# Generated by Django 6.0.2 on 2026-03-01 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aula',
            name='nombre',
            field=models.CharField(help_text='Ej: 101 NP, 203 AP, LAB 2', max_length=20, verbose_name='Nombre del Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='vacantes',
            field=models.PositiveIntegerField(default=0, help_text='Capacidad máxima de alumnos', verbose_name='Vacantes'),
        ),
        migrations.AlterUniqueTogether(
            name='aula',
            unique_together={('nombre', 'pabellon')},
        ),
    ]
