# Generated by Django 6.0.2 on 2026-03-09 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aulas', '0002_alter_aula_nombre_alter_aula_vacantes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='tipo_sesion',
        ),
        migrations.AddField(
            model_name='aula',
            name='tipo',
            field=models.CharField(choices=[('A', 'Aula'), ('L', 'Laboratorio')], default='A', max_length=1, verbose_name='Tipo de Aula'),
        ),
        migrations.AlterField(
            model_name='aula',
            name='vacantes',
            field=models.PositiveIntegerField(help_text='Capacidad máxima de alumnos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vacantes'),
        ),
    ]
