# Generated by Django 6.0.1 on 2026-02-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docentes', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='horarios_asignados', to='docentes.docente'),
        ),
    ]
