# Generated by Django 6.0.1 on 2026-01-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='tipo',
            field=models.CharField(choices=[('T', 'Teoría'), ('P', 'Práctica'), ('L', 'Laboratorio')], default='T', max_length=1, verbose_name='Tipo de sesión'),
        ),
    ]
