# Generated by Django 6.0.1 on 2026-02-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grupos', '0002_remove_grupo_docente'),
        ('horarios', '0002_horario_docente'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('grupo', 'dia', 'hora_inicio')},
        ),
    ]
