# Generated by Django 6.0.2 on 2026-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_alter_horario_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together=set(),
        ),
    ]
